[feat/week4] compose 필수과제
NOW-SOPT-ANDROID/yeonjeen-lee pull request #10
Opened 2024-05-03 13:24 UTC by yeonjeen

## Related issue 🛠
- closed #8

## Work Description ✏️
- [ ] 회원가입 성공 조건 추가
- [ ] Home reqres 서버 연결

## Screenshot 📸
[4주차 시현영상.webm](https://github.com/NOW-SOPT-ANDROID/yeonjeen-lee/assets/144861180/dcd6b855-ecf4-439b-9d3c-80fb596ce788)

## To Reviewer
죄송합니다...

2024-05-05 01:09 UTC, arinming reviewed
리팩토링 으썃~~~~

2024-05-05 14:32 UTC, junseo511 requested changes
선생님!! 마무리까지 가주세요~~🫠

2024-05-05 14:32 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/Data/ApiFactory.kt
> +    }
xml 에서 말씀드린 것처럼 재활용 가능할 것 같아요~~

2024-05-05 14:32 UTC, junseo511 commented on app/build.gradle
> +    implementation 'com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0'
기능별로 정리해서 주석 추가해주시면 좋을듯 합니다~~!!!!

2024-05-06 17:20 UTC, murjune requested changes
안녕하세요. 연진님 리뷰어로 함께하게 된 명예OB 이준원입니다.

아직 과제 완수를 하지 않으신 것 같습니다.(워낙 양이 많았으니 이해가 갑니다..)

과제를 다 완수하시면 리뷰 요청 부탁드려요! 💪

2024-05-24 15:05 UTC, merged