[feat/week1] 필수과제 xml
NOW-SOPT-ANDROID/yeonjeen-lee pull request #3
Opened 2024-04-04 11:46 UTC by yeonjeen

## Related issue 🛠
- closed #2 

## Work Description ✏️
- [ ] 회원가입 구현
- [ ] 로그인 구현
- [ ] 메인(마이페이지) 구현

## Screenshot 📸
[Screen_recording_20240404_204554.webm](https://github.com/NOW-SOPT-ANDROID/yeonjeen-lee/assets/144861180/ee5eac19-fa51-4d94-9c63-b0ea418f8dea)

2024-04-04 15:04 UTC, junseo511 approved these changes
오랜만의 과제 고생하셨습니다~~ 저희 이제 같이 컴포즈로 고통받아보죠 🥲

2024-04-04 15:04 UTC, junseo511 commented on app/build.gradle
> +        compose true
엥? 여기 xml PR 아니었나요

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/AndroidManifest.xml
> +            android:name=".Activity.SignUpActivity"/>
이친구들 순서가 LoginActivity랑 다른거같군요!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +    }
이친구가 조금 많은 일을 하고 있지는 않나요?!

그에 대한 함수명으로 setupLogin이라는 이름도 약간 추상적으로 보입니다!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        val extras = Bundle()
번들로 묶어서 넘겨주는 방식은 좋은 것 같아요!

But, extras라는 이름만으로 Bundle인 것은 알기 어려울 것 같습니다 🤔

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +    private fun createMainActivityExtras(savedId: String?, savedPassword: String?): Bundle {
메인 액티비티의 엑스트라~를 만들어준다는 느낌보다

실제 하는 역할은 유저 정보에 대한 번들을 만들어주는 느낌이 강하지 않나요?

함수명이나 변수명에 대해 좋은 [레퍼런스 사이트](https://grep.app/)가 있습니다

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/MainActivity.kt
> +        binding.tvMainMbti.text = mbti
이 친구를 좀 더 간결하게 만들 수 있는 방법이 없을까요?

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
로그인과 회원가입에 대한 함수명과 동작이 일관성이 필요할 것 같아요!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
이런 방식을 사용하면 SignUpActivity를 거치지 않고서는 로그인이 어려울 것 같습니다!

더 좋은 방법이 없을까요?

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        extras.putString("mbti", intent.getStringExtra("mbti"))
이 친구들의 가독성을 높일 수 있는 방법은 없을까요?

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +            val selectedMbti = binding.spSignUpMbti.selectedItem.toString()
현재 모든 액티비티에서 재사용되고 있는데 재사용성을 높이는 방안이 없을까요?

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +    private val MAX_PASSWORD_LENGTH = 12
val 이 아닌 다르게 선언하는 방식도 있습니다!! const val이 뭘까요?

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +        val passwordLengthValid = password.length in MIN_PASSWORD_LENGTH..MAX_PASSWORD_LENGTH
가독성을 높이려 했던 시도 아주 좋습니다 👍👍

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:textSize="25dp"
Command + Option + L

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:text="@string/welcome_to_sopt"
하드코딩을 용서하지 않는 습관 좋습니다~~

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/etLoginPs"
[객체 지향 생활 체조 원칙](https://jamie95.tistory.com/99) 5장을 참고하세요~~

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvLoginPsTitle"/>
어딘가 허전하지 않나요? 과제 조건을 잘 읽어보세요!!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/tvMainSelfcription"
여기도 ~~ 위에 올린 객체 지향 어쩌구 참고해주세요 😄

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/layout/activity_signup.xml
> +        app:layout_constraintStart_toStartOf="@id/tvSignUpMbtiTitle"/>
다채로운 머티리얼을 쓰고자 한 모습 아주 좋아요~~!!!!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_English">SIGN UP</string>
변수명에 대한 일관성이 조금 부족해 보이지 않나요?!

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +        val mbtiTypes = resources.getStringArray(R.array.mbti_type)
Array를 활용해서 정해진 변수를 한정해둔 시도 좋네요~~

2024-04-04 15:04 UTC, junseo511 commented on app/src/main/res/values/arrays.xml
> +    </string-array>
enum class에 대해서도 알아볼까요? enum class를 어떨때 사용할까요?

2024-04-04 15:04 UTC, junseo511 commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
버전을 내린 이유가 있나요?

2024-04-05 08:23 UTC, arinming reviewed
가독성을 높이기 위한 시도들이 많이 보여서 코드 읽기가 너무 편했습니당!

2024-04-05 08:23 UTC, arinming commented on app/src/main/res/layout/activity_signup.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvSignUpPsTitle"/>
여기도 과제 조건 확인해보는 거 어떨가용!

2024-04-05 08:23 UTC, arinming commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_English">SIGN UP</string>
> 변수명에 대한 일관성이 조금 부족해 보이지 않나요?!

섬세하시다!

2024-04-05 08:23 UTC, arinming commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +    private val MAX_PASSWORD_LENGTH = 12
companion object로 상수 선언하는 데 익숙해지고 싶네욥

2024-04-05 08:23 UTC, arinming commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +        val passwordLengthValid = password.length in MIN_PASSWORD_LENGTH..MAX_PASSWORD_LENGTH
한 수 배웁니다..

2024-04-05 18:49 UTC, junseo511 requested changes
선생님 그 브랜치 바꿔주시면 어푸해드릴게요 🤣

2024-04-07 07:26 UTC, SYAAINN reviewed
보다보니 YOB의 연륜이 느껴지는 것 같았습니다..! 잘 배우고 갑니다!

2024-04-07 07:26 UTC, SYAAINN commented on app/build.gradle
> +        buildConfig true
이 줄은 어떤 기능을 하는지 알 수 있을까요?

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +                moveToMainActivity(savedId, savedPassword)
페이지를 이동해주는 함수가 goToSignUp() 과 moveToMainActivity() 로 비슷한 기능이지만 이름이 다른데 통일해보는건 어떨까요?

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +    }
유효성을 검증하는 기능이라는 걸 잘 보여줄 만한 이름.. check, valid 같은 이름은 어떠신가요?!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        extras.putString("mbti", intent.getStringExtra("mbti"))
아린님 코드를 with(binding)을 이용해 묶어놔서 가독성이 높아보였는데, 여기도 with(extras) 블럭으로 묶는게 가능할까요? 궁금합니다..!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/MainActivity.kt
> +        binding.tvMainMbti.text = mbti
오오 여기를 with(binding) 으로 묶어보면 어떨까요?!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        extras.putString("mbti", intent.getStringExtra("mbti"))
아이디 패스워드는 위에서 받아놓고 사용하는데 닉네임과 mbti 는 여기서 받고 있네요! 메모리 관련 이슈가 있을까 싶어서 이렇게 하신걸까요? 통일감을 줄 수 있는 방법에는 어떤게 있을까요?

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
토스트 생성 부분을 함수화해서 재사용하는 방법이 있던데 아린님 코드 참고해보시면 좋을 것 같습니다!!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
회원가입을 검증하는 함수와 로그인 화면으로 이동하는 함수 모두 id, pw, nickname, mbti 매개변수를 다 받아서 움직이고 있는데, 함수 작성 과정이 무거워 보이는 것 같습니다! 매개변수의 개수에 관련해 메모리 관련 이슈는 없을 지 궁금합니다!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ViewModel/LoginViewModel.kt
ViewModel 까지 사용하다니 .. YOB의 면모가 여기서 보이는군요 ... !!!!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +    private val MAX_PASSWORD_LENGTH = 12
상수에 의미를 부여해주는 디테일 본받고 싶어요!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +        val passwordLengthValid = password.length in MIN_PASSWORD_LENGTH..MAX_PASSWORD_LENGTH
함수명도 깔끔하고 검증 과정도 깔끔하네요 멋있는 함수에요!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/res/layout/activity_login.xml
> +        android:text="@string/welcome_to_sopt"
스트링 추출을 하라는게 이런 뜻이였군요! 명심하겠습니다 ㅎㅎ

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/etLoginPs"
ps 도 좋지만 pw 는 어떨까요?!

2024-04-07 07:26 UTC, SYAAINN commented on app/src/main/res/layout/activity_signup.xml
> +        app:layout_constraintStart_toStartOf="@id/tvSignUpMbtiTitle"/>
저는 EditText 만 쓰기 바빴는데 MBTI를 심심하게 입력하는게 아니라 Spinner를 사용해서 선택하게 한게 재밌어요!

2024-04-07 14:36 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        extras.putString("mbti", intent.getStringExtra("mbti"))
with 여기서도 가능할겁니다...!

2024-04-17 14:55 UTC, yeonjeen commented on app/build.gradle
> +        compose true
삭제했습니다!

2024-04-17 14:55 UTC, yeonjeen commented on app/src/main/AndroidManifest.xml
> +            android:name=".Activity.SignUpActivity"/>
변경했습니다!

2024-04-17 14:56 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +    }
반영해보겠습니당!

2024-04-18 02:06 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +            val selectedMbti = binding.spSignUpMbti.selectedItem.toString()
싱글톤 객체로 만들어서 재사용해보겠습니다!

2024-04-18 03:15 UTC, junseo511 approved these changes
천천히 다음 과제로 넘어가보시죠!!! 어프 아직 안한줄 몰랐네요 죄송,,,🥺

2024-04-18 06:34 UTC, merged