[feat/week1] 필수과제 compose
NOW-SOPT-ANDROID/yeonjeen-lee pull request #4
Opened 2024-04-05 15:02 UTC by yeonjeen

2024-04-07 12:42 UTC, arinming reviewed
컴포즈 재밌다고 하셨던게 기억나네요 ㅎㅎ 재사용성 높이려고 하신 게 보여서 너무 좋았습니닷.

2024-04-07 12:42 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        SignUpField("주소", address)
요기 컴포넌트 통일하신거 굿굿입니당

2024-04-07 12:42 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +            viewModel.signUp(id, password, nickname, address)
벌써 뷰모델을!!!!!!!

2024-04-07 12:42 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
>  }
요 코드는 없어도 될 것 같넹요!

2024-04-07 12:42 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignUpViewModel.kt
> +    }
뷰모델부터 상수화까지 정말 깔끔함니다.

2024-04-07 15:38 UTC, junseo511 requested changes
고생,,,많으셨습니다 2주차 과제 마감까지 조금 남았으니
조건 맞춰서 천천히 리팩토링 진행해보도록 하죠~~

2024-04-07 15:38 UTC, junseo511 commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
저희 싱글액티비티,,, 성공할 수 있겠죠?!

2024-04-07 15:38 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +                    LoginContent(viewModel, signUpId, signUpPassword, signUpNickname, signUpAddress)
컴포즈에서는 Screen이란 표현을 주로 사용하는 것 같아요~~!

2024-04-07 15:38 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/LoginViewModel.kt
> +}
저는 뷰모델 적용할 엄두를 못냈는데 도전하신 것에 박수를~~👏

2024-04-07 15:38 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +        val signUpAddress = intent.getStringExtra("ADDRESS") ?: ""
orEmpty()를 써보시는 것은 어떨까요?

2024-04-11 06:06 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +        SignUpField("주소", address)
로그인도 함 적용해보겠슴당

2024-04-11 06:06 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +            viewModel.signUp(id, password, nickname, address)
???: 뷰모델은 어디서도 사용 가능해야한다

2024-04-11 06:06 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
>  }
앗 넹!!

2024-04-11 06:07 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignUpViewModel.kt
> +    }
감사합니당(꾸벅)

2024-04-11 06:07 UTC, yeonjeen commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
...maybe?

2024-04-11 06:07 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/LoginActivity.kt
> +                    LoginContent(viewModel, signUpId, signUpPassword, signUpNickname, signUpAddress)
글쿤용 적용하겠습니당

2024-04-11 23:51 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/LoginViewModel.kt
> +}
근데 아직 뭔가..? 제대로 적용을 못하는 부분들이 있는 것 같아용..

2024-04-11 23:51 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +        val signUpAddress = intent.getStringExtra("ADDRESS") ?: ""
앗 넵! 적용해보겟습니다

2024-04-18 03:46 UTC, junseo511 approved these changes
리사이클러뷰 넣으시면서 회원가입 같이 보완해보시죠~~!!!!

2024-04-18 06:34 UTC, merged