[feat/week4] xml 필수과제
NOW-SOPT-ANDROID/yeonjeen-lee pull request #9
Opened 2024-05-02 19:59 UTC by yeonjeen

## Related issue 🛠
- closed #8

## Work Description ✏️
- [ ] 회원가입 성공 조건 추가
- [ ] Home reqres 서버 연결

## Screenshot 📸
[4주차 시현영상.webm](https://github.com/NOW-SOPT-ANDROID/yeonjeen-lee/assets/144861180/dcd6b855-ecf4-439b-9d3c-80fb596ce788)

## To Reviewer
제가 진짜 멍청이슈가... 한 번에 커밋을 날려버리다니... 죄송합니다,,,,,,,

2024-05-05 01:07 UTC, arinming reviewed
여행가서까지 수고많았던...

2024-05-05 01:07 UTC, arinming commented on app/build.gradle
> +        buildConfig true
여기에 buildConfig가 두 개 있네여 ㅎㅎ

2024-05-05 01:07 UTC, arinming commented on app/src/main/java/com/sopt/now/Activity/MainActivity.kt
> +    }
서버 통신 말고 intent로 데이터를 호출하는 이유가 궁금합니당

2024-05-05 01:07 UTC, arinming commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
여기 주석이써요~~~!

2024-05-05 01:07 UTC, arinming commented on app/src/main/java/com/sopt/now/adapter/FriendDiffCallback.kt
> +}
우왕 이 파일은 어떤 기능을 하나요?!

2024-05-05 01:07 UTC, arinming commented on app/src/main/java/com/sopt/now/data/FriendRequestDto.kt
> +    val page: Int=1,
여기 초기화하신 이유가 있나영?

2024-05-05 10:03 UTC, SYAAINN reviewed
아직 전 주차 과제들의 흔적이 남아있군요 ㅋㅋㅋㅋㅋ 우리 같이 야금야금 리팩 들어갑시다!

2024-05-05 10:03 UTC, SYAAINN commented on app/build.gradle
> +        buildConfig true
ㅋㅋㅋㅋ 예리했다

2024-05-05 10:03 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/ViewModel/LoginViewModel.kt
> +}
이제 이 친구는 필요 없어진 것 같은데 맞을까요?!

2024-05-05 10:03 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/adapter/FriendDiffCallback.kt
> +}
오.. 저도 줄 서봅니다!

2024-05-05 10:03 UTC, SYAAINN commented on app/src/main/java/com/sopt/now/data/FriendResponseDto.kt
> +    @SerialName("total_pages") val total_pages: Int,
홈페이지 API 명세와 순서를 맞추면 보기가 더 편할 것 같아요!

2024-05-05 14:28 UTC, junseo511 requested changes
바쁘셨을텐데 고생 많으셨습니다~~!!!

리팩 이후에 말씀해주시면 어푸해드릴게요 파이팅입니다 🤭

2024-05-05 14:28 UTC, junseo511 commented on app/build.gradle
> +// define any required OkHttp artifacts without version
불필요한 주석 지워주세용~~

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +        viewModel = ViewModelProvider(this).get(LoginViewModel::class.java)
오호 get으로 쓰면 어떤 점이 다르죠?

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ViewModel/LoginViewModel.kt
> +}
그러게용~~

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    private fun initObserver() {
어떤 옵저버인지 함수명을 보고 알기 어렵네요

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/ViewModel/HomeViewModel.kt
> +                        }
여기서 매핑을 진행하시는 이유가 있나요?

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/ApiFactory.kt
> +    }
이친구를 재사용해서 묶어볼 수 있을 것 같습니다!!

2024-05-05 14:28 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/FriendRequestDto.kt
> +    val page: Int=1,
2222

2024-05-05 14:30 UTC, junseo511 commented
그리고 머지 브랜치 확인해주세요~~!!!

2024-05-09 18:50 UTC, briandr97 requested changes
안녕하세요 연진님, 연진님의 리뷰어를 맡게된 권용민이라고 합니다!

필수 과제에 xml과 compose가 있는데요 xml은 제가, compose는 준원님께서 리뷰해주실 예정입니다.
코드에 정답이 없으며, 저희 또한 많이 부족한 사람이므로 공통 로직에서 저와 준원님의 의견이 상충될 수 있습니다. 혹시 그런 상황이 발생한다면, 연진님께서 생각하시는대로 진행하고 말씀해주시면 됩니다!

또 제가 리뷰해드린 내용이라고 해서 정답은 아닙니다. 사람마다 생각이 다를 수 있으며, 제가 틀렸을 수도 있습니다. 납득이 되지 않으면 언제든 질문주시고, 연진님의 생각을 말씀해주세요!

과제하느라 고생하셨습니다! 잘부탁드립니다!

모든 리뷰에 1~5에 해당하는 번호를 남겼습니다. 해당 번호들은 중요도를 나타냅니다.
1,2번은 changes requested,
3번은 comment,
4,5번은 추가정보 정도로 생각해주시면 좋을 것 같습니다.

- - -

코드가 담백해서 리뷰할만한 내용이 많지 않아서 전체 리뷰 및 추가적으로 생각해볼만한 내용을 남깁니다.
- 패키징을 다시 생각해보시면 좋을 것 같습니다.
    - 지금 성격이 비슷한 클래스들 끼리 모아놓으신 것으로 보입니다. 어차피 제가 말하지 않아도 앞으로 개발해나가면서 느끼시겠지만, 타입이 비슷한 클래스보다는 같은 피쳐(기능)을 담당하는 파일들끼리 모아놓는 것이 더 편할 것이라고 생각합니다. 물론 제 개인적인 의견이므로 앞으로 개발하시면서 알아가는 것도 좋다고 생각합니다.
- `ViewModel`을 사용해주셨는데, 어떤 생각에서 사용하게 되셨는지 궁금합니다. 
    - 혹여 MVVM을 적용하고 싶으셨다면, _왜 적용하고 싶었는지_, _MVVM이란 무엇인지_, _현재 상속받고 있는 `ViewModel`클래스는 왜 상속받는지_ 에 대해 생각해보시고 답변해주시면 좋을 것 같습니다.

2024-05-09 18:50 UTC, briandr97 commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +            Toast.makeText(this, "로그인에 성공했습니다.", Toast.LENGTH_SHORT).show()
[2]
문자를 하드 코딩하는 것과 `strings.xml`에 넣고 불러오는 것은 어떤 기준으로 나누셨나요?

2024-05-09 18:50 UTC, briandr97 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +                state.message,
[2]
위와 같은 리뷰입니다.
> 문자를 하드 코딩하는 것과 strings.xml에 넣고 불러오는 것은 어떤 기준으로 나누셨나요?

2024-05-09 18:50 UTC, briandr97 commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
[5]
만약 다른 개발자가 로그인 액티비티를 시작할때 어떤 값들을 전달해야 하는지 헷갈리면 어떻게 될까요?
로그인 액티비티에서 필요한 값들을 필수적으로 받을 방법은 없을까요?

2024-05-09 18:50 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +    val liveData = MutableLiveData<SignUpState>()
[3]
변수가 자신이 담고있는 정보가 아닌 타입을 나타내고 있습니다.
만약 다른 개발자가 외부에서(ex. 액티비티) 이 변수를 활용한 코드를 봤다면, 어떤 의미인지 바로 파악할 수 있을까요?

2024-05-09 18:50 UTC, briandr97 commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +                        message = "회원가입 성공 유저의 ID는 $userId 입니둥"
아까 위에서 했던 리뷰와 같습니다. (문자열 하드코딩 기준)

2024-05-23 19:54 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +            Toast.makeText(this, "로그인에 성공했습니다.", Toast.LENGTH_SHORT).show()
의도해서 나눈 것은 아닙니다! 미쳐 다 반영하지 못한 부분이 있었던 것 같습니다...!

2024-05-23 20:11 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/Activity/LoginActivity.kt
> +            Toast.makeText(this, "로그인에 성공했습니다.", Toast.LENGTH_SHORT).show()
그리고 너무 늦게 답변을 드려서 죄송합니다...!  이것저것 하다보니 답변이 너무 늦었네요,,, 빠르게 답변 달고 반영해보도록 하겠습니다!! 시간내서 코리 달아주셔서 감사합니다(꾸벅)

2024-05-23 21:12 UTC, yeonjeen commented
> 안녕하세요 연진님, 연진님의 리뷰어를 맡게된 권용민이라고 합니다!
> 
> 필수 과제에 xml과 compose가 있는데요 xml은 제가, compose는 준원님께서 리뷰해주실 예정입니다. 코드에 정답이 없으며, 저희 또한 많이 부족한 사람이므로 공통 로직에서 저와 준원님의 의견이 상충될 수 있습니다. 혹시 그런 상황이 발생한다면, 연진님께서 생각하시는대로 진행하고 말씀해주시면 됩니다!
> 
> 또 제가 리뷰해드린 내용이라고 해서 정답은 아닙니다. 사람마다 생각이 다를 수 있으며, 제가 틀렸을 수도 있습니다. 납득이 되지 않으면 언제든 질문주시고, 연진님의 생각을 말씀해주세요!
> 
> 과제하느라 고생하셨습니다! 잘부탁드립니다!
> 
> 모든 리뷰에 1~5에 해당하는 번호를 남겼습니다. 해당 번호들은 중요도를 나타냅니다. 1,2번은 changes requested, 3번은 comment, 4,5번은 추가정보 정도로 생각해주시면 좋을 것 같습니다.
> 
> 코드가 담백해서 리뷰할만한 내용이 많지 않아서 전체 리뷰 및 추가적으로 생각해볼만한 내용을 남깁니다.
> 
> * 패키징을 다시 생각해보시면 좋을 것 같습니다.
>   
>   * 지금 성격이 비슷한 클래스들 끼리 모아놓으신 것으로 보입니다. 어차피 제가 말하지 않아도 앞으로 개발해나가면서 느끼시겠지만, 타입이 비슷한 클래스보다는 같은 피쳐(기능)을 담당하는 파일들끼리 모아놓는 것이 더 편할 것이라고 생각합니다. 물론 제 개인적인 의견이므로 앞으로 개발하시면서 알아가는 것도 좋다고 생각합니다.
> * `ViewModel`을 사용해주셨는데, 어떤 생각에서 사용하게 되셨는지 궁금합니다.
>   
>   * 혹여 MVVM을 적용하고 싶으셨다면, _왜 적용하고 싶었는지_, _MVVM이란 무엇인지_, _현재 상속받고 있는 `ViewModel`클래스는 왜 상속받는지_ 에 대해 생각해보시고 답변해주시면 좋을 것 같습니다.

1. 패키징 관련해서는 저도 다른 프로젝트들의 패키지를 보고 문제점을 인식하고 있었습니다! 그래서 이번에 다시 패키지를 분리해보았습니다!

2. 
안드로이드 개발을 처음 시작했을 때는 모든 코드를 Activity 안에 넣곤 했습니다. 그러나 기능이 많아지면서 Activity 안의 코드가 점점 늘어나게 되었고, 결국 제가 작성한 코드임에도 불구하고 이해하기 어려운 상황이 자주 발생했습니다. 또한 그렇게 늘어난 코드에 또 다른 기능을 추가하거나 수정해야 하는 경우 Activity 안에 있는 모든 코드들을 건드려야 하는 문제점도 있었습니다. 그래서 '코드 분리'의 필요성을 느끼게 되었고, 세미나를 통해 ViewModel에 대해 배우면서 MVVM 패턴을 적용하게 되었습니다.

저는 프로젝트가 단순한 일회성이 아닌, 새로운 기능이 추가될 확장성과 유지보수성을 모두 염두에 두어야 한다고 생각합니다. 이를 위해 뷰와 모델을 분리하고, 그 사이에 뷰모델을 두어 비즈니스 로직을 처리하는 MVVM 패턴을 적용하고자 했습니다.

MVVM에 대해서 완벽하게 이해했다고 이야기  할 수는 없지만 MVVM이란 소프트웨어 아키텍처 패턴으로 앞에서 말씀드렸던 것처럼 확장성과 유지보수성을 위해 ui로직과 비즈니스로직을 분리하는 것에 그 목적이 있습니다. 그 중에서도 질문을 주신 뷰모델의 경우는 뷰와 모델의 중간 역할로서 뷰의 데이터 바인딩을 관리하고 뷰와 모델간의 통신을 담당하기도 합니다. 또한 모델 즉 데이터의 변화를 감지하여 뷰에 반영될 수 있도록 해주는 역할을 하고 있습니다. 

그리고 마지막으로 질문주신 '현재 상속받고 있는 뷰모델 클래스는 왜 상속 받는지'에 대한 질문이 결국 해당 뷰모델이 액티비티나 프래그먼트에 상속되어져 어떤 역할을 하고 있는지를 물어보신 거라면 현재 제가 구현한 뷰모델을 기준으로 보자면 로그인이나 회원가입을 위한 비지니스로직을 처리하거나 서버통신을 위해 상속받고 있습니다. 

질문주신 부분에 대해서 제가 알고 있는 선에서 답을 해보았습니다,,,ㅎ 혹시 제가 잘못 알고 있는 부분이 있거나 부족한 부분이 있다면 피드백 주시면 감사하겠습니다!!(꾸벅)

2024-05-24 05:20 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/Activity/SignUpActivity.kt
> +    }
코드의 정확성과 안전성을 위해 고려하면 좋을 사항인 것 같습니다! 필수적으로 받기 위해서는 정적메서드를 추가하거나 데이터 클래스로 필요한 객체들을 묶어서 전달하는 방법 등이 있을 수 있을 것 같습니다!

2024-05-24 05:25 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/ViewModel/SignUpViewModel.kt
> +    val liveData = MutableLiveData<SignUpState>()
말씀해주신 것처럼 다른 개발자가 해당 변수를 보았을 때 어떤 의미인지 파악하는데 어려움이 있을 수 있을 것 같습니다..! 해당 liveData는 회원가입 상태를 담고 있기 때문에 그런 역할이 잘 드러날 수 있도록 직관적으로 변수명을 수정 할 필요가 있을 것 같습니다! 반영해보도록 하겠습니다!!

2024-05-24 14:09 UTC, merged